# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fde95d2a4a667b4b20bb20a31752d3fc6d55e23c0695c2ff2fe8dced9eba7e7d2ec38620cf81770c912cb73d41f3e9602a5b317f118e49ea012f4e1933a1fc6

test:
  secret_key_base: 28160899037d47494fa3188254839a02281bdfa9bb2491c39d690219193b9b29914d93fd904a0b64ef4448deef2551d4fa2f80b9f02247d18315fb0684e354a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
